const balance = document.getElementById('balance')
const money_plus = document.getElementById('money-plus')
const money_minus = document.getElementById('money-minus')
const list = document.getElementById('list')
const from = document.getElementById('from')
const text = document.getElementById('text')
const amount = document.getElementById('amount')